#! /bin/bash
# dwm status bar script

# How often to update the status bar
POLLDELAY=0.5
# Battery low threshold
BATTERYLOW=90

# Wifi status and details
wifi()
(
	echo $(wicd-cli --wireless -d | grep "IP\|Essid\|Quality" | tr '\n' ' ' | awk '{ printf "%s %s %s%%", $2, $4, $6 }')
)

# Status bar time and date in the user's locale
timedate()
(	
	echo $(date +"%c")
)

# Print battery status, charge and time remaining
battery()
(
	# Get the battery string
	returnstring=$(acpi -b | awk '{sub(/,/, ""); sub(/%,/, "%"); printf "%s %s (%s %s %s)", $3,$4,$5,$6,$7,$8}' | sed 's/ )/)/g')
	powerlevel=$(echo $returnstring | awk '{ sub(/%/, ""); print $2 }')
	status=$(echo $returnstring | awk '{ print $1 }')

	# TODO add battery low warning
	echo $returnstring
)

# Get CPU temps
temp()
(
	echo $(sensors | awk '/Core/ {print $3}' | sed 's/[^a-zA-Z0-9.: ]//g' | tr '\n' ' ')
)

# Get CPU frequency
cpufreq()
(
	echo $(cpupower --cpu all frequency-info | awk '/current CPU frequency/ {print $5, $6}' | tr '\n' ' ' | sed 's/GHz./GHz/g')
)

# Get RAM info
memory()
(
	echo $(free | awk '/Mem/ {printf "%d MB/%d MB (%d MB free)\n", $3 / 1024.0, $2 / 1024.0, $4 / 1024.0 }')
)

# Get volume level
volume()
(
	echo $(amixer get Master playback | awk '/Mono:/ { print $4 }')
)

# Only display modules that output something
statusbar()
(
	final="| "
	modules=$1
	for output in "${modules[@]}"
	do
		if [ -n "$($output)" ]; then
			final+=" $($output) |"
		fi
	done
	echo $final
)

# Kill any rogue processes
for i in $(pidof -x $0)
do
	if [ "$i" -ne "$$" ]; then
		kill -9 $i
	fi
done
killall sleep

# Start sound drivers
start-pulseaudio-x11 &

# Modules to display, in order
modules=( wifi memory cpufreq temp battery timedate )

# Display the status bar
while true ; do
	xsetroot -name "$(statusbar $modules)"
	sleep $POLLDELAY
done &

# Start dwm
exec /usr/local/bin/dwm
